export { SkeletonBlock } from './SkeletonBlock'
export type { SkeletonBlockProps } from './SkeletonBlock'
export { SkeletonText } from './SkeletonText'
export type { SkeletonTextProps } from './SkeletonText'
export { SkeletonAvatar } from './SkeletonAvatar'
export type { SkeletonAvatarProps } from './SkeletonAvatar'
export { SkeletonTable } from './SkeletonTable'
export type { SkeletonTableProps } from './SkeletonTable'

// Card-level skeletons — exact shape matches for zero CLS
export { SkeletonUserCard } from './SkeletonUserCard'
export { SkeletonRoleCard } from './SkeletonRoleCard'
export { SkeletonAppCard } from './SkeletonAppCard'
export { SkeletonStatCard } from './SkeletonStatCard'
export { SkeletonAuditRow } from './SkeletonAuditRow'
export { SkeletonOverviewActivity } from './SkeletonOverviewActivity'
export { SkeletonDashboardWidget } from './SkeletonDashboardWidget'
export { SkeletonDonutChart } from './SkeletonDonutChart'
